### ISSUE TITLE
Snapshot created - full crawling again?

### ISSUE THREAD

**Issue by SampsonF** [Zygo/bees#179]
An existing readonly subvol is fully crawled and deduped.  

Now, I created a rw snapshot of it.

Immediately, bees started to crawl against this new subvol.

If the original subvol takes 24 hours to crawl and dedup.  Will this new snapshot take the same time to crawl and dedup?

Anyway to avoid or speed up this?

**Comment by Zygo** [comment]
New subvols are crawled starting from the lowest `min_transid` of any existing subvol.  If all other subvols were fully crawled, then a new subvol will start from the current filesystem transaction.

The search will skip any old extents in the new subvol.  It should be much faster on later passes.  If bees is fully caught up, a new subvol scan will take milliseconds.

**Comment by SampsonF** [comment]
Thank you very much!

Exactly as you said, the new subvol crawl finished almost immediately.
