### ISSUE TITLE
Question: Can Bees prevent my laptop from going to sleep?

### ISSUE THREAD

**Issue by camdenorrb** [Zygo/bees#228]
I'm currently running bees through the system unit file and I'm running into issues where my laptop fails to fall asleep, going through the logs I see that `beesd` is still attempting to crawl so was wondering if it could be the cause?

Any ideas?

**Comment by kakra** [comment]
Use `systemd-inhibit`.

**Comment by camdenorrb** [comment]
It appears that it was my kernel version that was causing this, was using 5.19 RC

Thank you for sharing that tho, interesting read @kakra
