### ISSUE TITLE
Missing commit from 2 years ago in v0.8 but in master???

### ISSUE THREAD

**Issue by agowa338** [Zygo/bees#242]
Hi, just noticed something strange. At least one commit from two years ago appears to be missing from the release v0.8 but it's in master. And it wasn't added after the cutoff. It was added two years ago.

I don't know if there are others missing, but this should be looked at by a maintainer.

The commit: https://github.com/Zygo/bees/commit/8aa343cecbc31a795e3ea555f19de7b4bcba8355
The file in master contains it as of two years ago: https://github.com/Zygo/bees/blame/master/scripts/beesd.in#L131
The file within tag v0.8: https://github.com/Zygo/bees/blame/v0.8/scripts/beesd.in#L131

Without this commit the crawl database won't get deleted when it's size was changed in the configuration file as expected.

But besides that it points to a much bigger problem, an issue with the history of this git project the branches diverged. Which may also affect other things.

I noticed this because alpine fetches the latest tag of this project for it's package (currently in testing within edge) and because the crawl db was not deleted (as it doens't contain the uuid within it's name).

Edit: After doing a branch diff (https://github.com/Zygo/bees/compare/v0.8...master) it is clear that it only affects two commits:
* https://github.com/Zygo/bees/commit/8aa343cecbc31a795e3ea555f19de7b4bcba8355
* https://github.com/Zygo/bees/commit/2427dd370eb28c39cefb597ac87d13c621fee95d

Both targeting the same file and the same line of code.

Edit2: This effects version all the way back to 0.7

**Comment by kakra** [comment]
This old commit was only merged after the release of v0.8. It was merged without rebase, thus the commit data stays old.

**Comment by agowa338** [comment]
Ok, that would explain it. Sorry for the fuzz then. Github could really show the merge commit. It really confused me right now.

**Comment by kakra** [comment]
Here it is: https://github.com/Zygo/bees/commit/64dab81e42cf1c396fc26d2a7f6a0893fbaacd1f
