### ISSUE TITLE
Re-built system, having issue with .beeshome

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [Zygo/bees#291]
I had to move all my stuff to a new partition to fix it, now beesd is not working, I am getting this error:
```
 beesd@root.service - Block-level BTRFS deduplication for root
Loaded: loaded (/etc/systemd/system/beesd@root.service; enabled; preset: enabled)
Active: failed (Result: exit-code) since Sun 2024-09-15 12:11:04 NZST; 2s ago
  Duration: 27ms
Invocation: 428c565b49e54675995e7a1a388f2c0c
   Process: 40699 ExecStart=/nix/store/7i9v6583vmbj3q2b53rwdyigyl44invi-bees-0.10/bin/bees-service-wrapper run LABEL=root verbosity=2 idxSizeMB=2048 workDir=.beeshome
-- --no-timestamps --loadavg-target 5.0 (code=exited, status=1/FAILURE)
   Process: 40732 ExecStopPost=/nix/store/7i9v6583vmbj3q2b53rwdyigyl44invi-bees-0.10/bin/bees-service-wrapper cleanup LABEL=root verbosity=2 idxSizeMB=2048 [workDir=.be](http://workdir=.be/)
eshome (code=exited, status=0/SUCCESS)
  Main PID: 40699 (code=exited, status=1/FAILURE)
IP: 0B in, 0B out
  Mem peak: 5.2M
CPU: 39ms

Sep 15 12:11:04 daspidercave systemd[1]: Started Block-level BTRFS deduplication for root.
Sep 15 12:11:04 daspidercave beesd[40699]: /run/bees/mnt/0095faf2-2359-4515-a1e1-af7ef6f11a0f/.beeshome exists but is not a subvolume
Sep 15 12:11:04 daspidercave systemd[1]: beesd@root.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 12:11:04 daspidercave systemd[1]: beesd@root.service: Failed with result 'exit-code'.
warning: error(s) occurred while switching to the new configuration
```
I tried a series of commands, making a .beeshome on /, making bind mounts between /run/<partitionid>, trying to make subvolumes, nothing works

I also wrote the issue here:
https://www.reddit.com/r/btrfs/comments/1fgzu6w/beesd_has_a_issue/

**Comment by kakra** [comment]
Change to the directory containing the `.beeshome` folder, then:
```bash
mv .beeshome .beeshome.old
btrfs sub create .beeshome
rsync -av .beeshome.old/. .beeshome/.
rm .beeshome/beeshash.dat # because the subvolumes differ
```

You didn't recreate the subvolume structure of your system while moving your data to a new partition.

bees will crawl all your data from scratch, expect some increased disk IO for a few hours or days. Also, expect bees to increase disk usage slightly during this time before finally cleaning up, so keep enough free space.

**Comment by SpiderUnderUrBed** [comment]
I am getting this issue:
```
[spiderunderurbed@daspidercave:/run/bees/mnt/0095faf2-2359-4515-a1e1-af7ef6f11a0f]$ btrfs sub create .beeshome
ERROR: not a btrfs filesystem: .

[spiderunderurbed@daspidercave:/run/bees/mnt/0095faf2-2359-4515-a1e1-af7ef6f11a0f]$ 

```
Which is strange because
`[spiderunderurbed@daspidercave:/run/bees/mnt/0095faf2-2359-4515-a1e1-af7ef6f11a0f]$ lsblk -o UUID,FSTYPE
UUID                                 FSTYPE
686107ef-b8a2-4301-9350-f69b9de9b81e btrfs
                                     
                                     
                                     BitLocker
AC5035B950358B5A                     ntfs
                                     
8642bd90-d6a5-4789-8095-42e9939a1374 swap
d7b25073-d690-4163-b3f0-5de410afe535 crypto_LUKS
C751-21FD                            vfat
0095faf2-2359-4515-a1e1-af7ef6f11a0f btrfs

`

**Comment by SpiderUnderUrBed** [comment]
It seems like /run/bees/mnt/ uses tmpfs, any way to change this in plasma or beesd? I am getting a whole host of issues.

**Comment by kakra** [comment]
`/run/bees/mnt/...` is only mounted while bees is running - and bees exits immediately because of the error. So try mounting subvolid=0 first:
```bash
mkdir /mnt/btrfs-pool
mount -o subvolid=0 UUID=0095faf2-2359-4515-a1e1-af7ef6f11a0f /mnt/btrfs-pool
```

Now try my above step in that directory.

**Comment by kakra** [comment]
Simply `btrfs sub create /mnt/btrfs-pool/.beeshome`. If it exists already, rename it first.

**Comment by SpiderUnderUrBed** [comment]
I made a few mistakes trying to clear out /mnt/btrfs-pool which lead to me requiring to re-install my system, regardless, the issue is fixed now.
