### ISSUE TITLE
one filesystem flag?

### ISSUE THREAD

**Issue by stroucki** [Zygo/bees#57]
Looking why the EXTENT_SAME ioctls are returning EINVAL, I notice that bees was looking at files from a different filesystem mount within btrfs space. Should there be a flag to not go over filesystem boundaries?

**Comment by Zygo** [comment]
If you have bees set up correctly it will not cross filesystem boundaries.  If you don't give bees the root of a btrfs, bees should detect that immediately and refuse to process the filesystem.  If something is mounted on top of the bees mount point, bees will detect that the metadata doesn't agree with the behavior of open() and refuse to process the data.  Directory traversals are done with openat() and O_NOFOLLOW to avoid filesystem races, and every opened FD is checked for consistency with the expected inode.  If you can get bees to stray from one btrfs filesystem to another and then run EXTENT_SAME there, _I would like to know how._

Can you describe your setup in more detail?

There is one known bug with EXTENT_SAME--when there is a hole between the first and second 4K block (i.e. inline extent, hole between end of extent and second 4K block, then regular extent), EXTENT_SAME returns EINVAL.  bees could theoretically check for that but it doesn't usually happen often enough to justify the extra code.

**Comment by stroucki** [comment]
I guess the simplest equivalent would be:
btrfs root subvol mounted on /tmp/brtfs
underneath, a subvol named jessie, so /tmp/btrfs/jessie
underneath that procfs mounted on /tmp/btrfs/jessie/proc
(so can do chroot stuff within)
When I ran bees on /tmp/btrfs, I saw proc files were being looked at.
I have bind mounted /tmp/btrfs on /tmp/x, and am running bees on /tmp/x now, and dedup seems to be proceeding.

**Comment by stroucki** [comment]
don't currently have a setup like this with a kernel compatible with bees, so closing for now.
