### ISSUE TITLE
Controlling logging severity

### ISSUE THREAD

**Issue by KristupasSavickas** [Zygo/bees#67]
Currently it seems like a lot of unnecessary information is being written to stdout (which in turn causes a log spam when used with systemd).  From quick look at the code, the concept of log levels seems to be implemented already, but I can't find a way to set the minimum level, so that all the ones below it are ignored. It would be nice if this could be controlled using command line arguments (and in turn via the config file).

**Comment by Zygo** [comment]
grep works... ;)

...but filtering that originates within the bees process would be better (it wouldn't have to run the expression that generates the log message).

**Comment by kakra** [comment]
When I implemented log levels, I also thought of filtering. But at that point, it made not quite sense because some logs without the others were sometimes out of context. Has this been fixed since? I know, you (@Zygo) reworked a lot of the loggings after my contribution so I guess it should be fine now.

**Comment by kakra** [comment]
BTW @KristupasSavickas Since beesd passes log levels to the systemd journal, you can use journald filtering on it:

    journalctl -p err -u beesd@XXXX.service

**Comment by Zygo** [comment]
Logs at level 7 (DEBUG) are mostly "bees started iterating over the filesystem" and "bees finished iterating over the filesystem".  Logs at level 6 (INFO) are individual dedup and copy operations.  Levels 3-5 (ERR..NOTICE) are more significant problems like IO errors, exception traces, etc.  Nothing in bees uses log levels 0..2.

PERFORMANCE and WORKAROUND warnings seem to be at the wrong level.  They should probably be NOTICE (level 5) to distinguish them from routine dedup messages.

I think any insufficient-context log messages should now be considered bugs:  either add context to the individual message, or change the message log level to match the other messages that give context.

There might be a use for a lower-level log message level (i.e. move everything up so DEBUG is available for very verbose logging); on the other hand, such information would only be useful for people debugging the code, and anyone who is doing that can just modify the source to include the required extra information and revert the change when done.

**Comment by Ratio2** [comment]
> BTW @KristupasSavickas Since beesd passes log levels to the systemd journal, you can use journald filtering on it:
> 
> ```
> journalctl -p err -u beesd@XXXX.service
> ```
To reduce unnecessary system log entries:
```
sudo systemctl edit beesd@....service
```
```
[Service]
LogLevelMax=notice
```
