### ISSUE TITLE
Linking ussie Ubuntu 16.04 (Server)

### ISSUE THREAD

**Issue by Nefelim4ag** [Zygo/bees#8]
Hi, i try compile bees for lab, and after i installing some missing headers i catch this:
```
g++ -Wall -Wextra -Werror -O3 -I../include -ggdb -fpic -std=c++11 -Wold-style-cast -o "../bin/bees" bees.o bees-context.o bees-hash.o bees-resolve.o bees-roots.o bees-thread.o bees-types.o  -L../lib -Wl,-rpath=/root/bees/lib -lcrucible -lpthread
../lib/libcrucible.so: undefined reference to `uuid_unparse'
collect2: error: ld returned 1 exit status
Makefile:36: recipe for target '../bin/bees' failed
```

May be i miss something?
```
# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```
```
# apt-cache policy uuid uuidcdef uuid-dev uuid-runtime libuuid1
uuid:
  Installed: 1.6.2-1.5build2
  Candidate: 1.6.2-1.5build2
  Version table:
 *** 1.6.2-1.5build2 500
        500 http://by.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
uuidcdef:
  Installed: 0.3.13-5
  Candidate: 0.3.13-5
  Version table:
 *** 0.3.13-5 500
        500 http://by.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
uuid-dev:
  Installed: 2.27.1-6ubuntu3.1
  Candidate: 2.27.1-6ubuntu3.1
  Version table:
 *** 2.27.1-6ubuntu3.1 500
        500 http://by.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.27.1-6ubuntu3 500
        500 http://by.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
uuid-runtime:
  Installed: 2.27.1-6ubuntu3.1
  Candidate: 2.27.1-6ubuntu3.1
  Version table:
 *** 2.27.1-6ubuntu3.1 500
        500 http://by.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.27.1-6ubuntu3 500
        500 http://by.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
libuuid1:
  Installed: 2.27.1-6ubuntu3.1
  Candidate: 2.27.1-6ubuntu3.1
  Version table:
 *** 2.27.1-6ubuntu3.1 500
        500 http://by.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.27.1-6ubuntu3 500
        500 http://by.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by Zygo** [comment]
It looks like you have the header for uuid-dev but not the library?

**Comment by PeeJay** [comment]
I was just about to report the same bug! I have no idea why it happens, but libcrucible.so doesn't link against libuuid. For some reason bees and test need to link against libuuid.
(Ubuntu 16.10)
peejay@peejay-virtual-machine:~/pj-server/bees/bees/bees$ ldd lib/libcrucible.so 
	linux-vdso.so.1 =>  (0x00007ffcf37fe000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2fbbe46000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2fbbb3d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2fbb926000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2fbb55d000)
	/lib64/ld-linux-x86-64.so.2 (0x000056127b969000)
(Gentoo)
vm-server bees # ldd ~/bees/lib/libcrucible.so
        linux-vdso.so.1 (0x00007ffdd3bf4000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007feccc8a1000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6 (0x00007feccc4a8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007feccc1ab000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgcc_s.so.1 (0x00007feccbf94000)
        libc.so.6 => /lib64/libc.so.6 (0x00007feccbbf8000)
        /lib64/ld-linux-x86-64.so.2 (0x0000559d12ab0000)

**Comment by Zygo** [comment]
I built a VM image of Ubuntu server 16.04 and I can reproduce the problem.  I don't *understand* the problem yet.

libuuid.so and libuuid.so.1 both contain the uuid_parse symbol and gcc does resolve the symbol for libcrucible.so; however, it doesn't put libuuid.so in the NEEDED section of libcrucible.so so the libuuid library isn't available later on.  I ran a build under `strace` and it seems to be doing all the right things, just with the wrong result at the end.

**Comment by Zygo** [comment]
FWIW bees only uses libuuid at one place, and that place is only needed if you had a v0.1 bees running.  You _could_ just delete that code.

Still, it would be nice to solve this, since it would affect any library bees might depend on in the future--and in the future, such libraries might not be as expendable as libuuid.
