### ISSUE TITLE
std::invalid_argument -  (core dumped) "$bees_bin" "${ARGUMENTS[@]}

### ISSUE THREAD

**Issue by bugsyb** [Zygo/bees#81]
All was working fine with: bees version v0.5-130-ge564d27
After upgrade to bees version v0.6-6-g14b35e3
Can't get it working due to below error (UUID is changed but matches what is in the config).

INFO: Find 61aaaa24-a25f-aad5-b3aa-d3ec97b9e5cd in /etc/bees//bees.conf, use as conf
INFO: Check: Disk exists
INFO: Check: Disk with btrfs
INFO: WORK DIR: /run/bees/
INFO: MOUNT DIR: /run/bees//mnt/61aaaa24-a25f-aad5-b3aa-d3ec97b9e5cd
bees version v0.6-6-g14b35e3
2018-10-15 01:25:24 10251.10251<3> bees: 
2018-10-15 01:25:24 10251.10251<3> bees: 
2018-10-15 01:25:24 10251.10251<3> bees: *** EXCEPTION ***
2018-10-15 01:25:24 10251.10251<3> bees: 	exception type std::invalid_argument: stoul
2018-10-15 01:25:24 10251.10251<3> bees: ***
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
/usr/sbin/beesd: line 145: 10251 Aborted                 (core dumped) "$bees_bin" "${ARGUMENTS[@]}" $OPTIONS "$MNT_DIR"

**Comment by bugsyb** [comment]
Error in UUID

**Comment by bugsyb** [comment]
Wrong UUID submit

**Comment by kakra** [comment]
I think this should not be closed, because even with a wrong UUID or mis-parsed cmdline, the daemon should not crash but exit gracefully with a proper error message...
